return {
{
    'Hello Commander. Welcome to our research base "BIG O". I am Professor Tuning, head of operations here. My schedule is packed with researching very important subjects, so I will try to be as concise as I can.',
    'Lately, we have been plagued by the strangest cosmic incidents. Two weeks ago, a large chunk of space debris entered the atmosphere on a direct collision course with these here facilities. Our planetary defense cannon was able to neutralize the threat. So far, nothing special. But then another one followed just a few days later. Ever since then, the frequency of these phenomena has steadily increased and we are starting to struggle to keep up defending against them.',
    'We are still trying to figure out why this is happening. My guess is that it is somehow related to the black-matter wave-emitter in ... oh .. I got a little carried away there. Please forget what I just said.\nAnyway, where was I? ... Ahhh yes ... like I said, my time is too valuable to be wasted on such miniscule matters.\nThis is your job: you are in charge of our defenses. Shoot down any junk that\'s approaching our base.\nGet to work, Commander!'
},
{
    'What in the name of Galileo is that?! This is unlike anything I have ever seen. Well ... shoot it, I guess.'
},
{
    'It is immune? How is that possible? You must not allow this "thing" to touch ground. Who knows what damage it could do? Shoot it!!!'
},
{
    'Oh no... Commander, this is terrible, terrible, terrible! You cannot even begin to imagine how valuable the research is that we are conducting here. While I am doing my part in trying to solve this conundrum, you please go ahead and do yours. SHOOT IT!'
},
{
    'Ok, so, one of my junior scientists suggested to recalibrate the algorithm of our cannon. Do you see these strange numbers on the side of this thing? They are actually generated by our computers. You see, our systems can pick up the faintest traces of energy waves and then transform them into a visual representation.',
    'So, anyway, he says that ... uhmmm ... it had something to do with a vulnerable spot... he mentioned searching for something?! Was it bilinar? No, no, no it was a "Lingual" search! I\'m perplexed. None of this makes any sense ... I am not sure if this will have any effect. But at this point, we might as well try it. Just shoot at it again. My colleague went ahead and took care of the re-calibration already.' 
},
{
    'I cannot believe this actually worked. The guy who developed the algorithm has handed me some documentation on it. As I said before, it is called a LINEAR SEARCH. I will make these Docs available to you as well. [TOP RIGHT CORNER - INFO]',
    'It seems the "attacks" have stopped for today. Good job, Commander. You arrived just in time. I cannot shake the feeling that we are in for a bumpy ride. Now, get some rest, but be prepared. We never know, when they might appear again.'
}
}